project_name: ravel
builds:
  - env: [CGO_ENABLED=0]
    main: ./cmd/ravel/ravel.go
    binary: ravel
    goos:
      - linux
    goarch:
      - amd64
  - env: [CGO_ENABLED=0]
    main: ./cmd/ravel-proxy/ravel.go
    binary: ravel-proxy
    goos:
      - linux
    goarch:
      - amd64
