project_name: ravel
version: 2
builds:
  - id : ravel
    env: [CGO_ENABLED=0]
    main: ./cmd/ravel/ravel.go
    binary: ravel
    goos:
      - linux
    goarch:
      - amd64
  - id : ravel-proxy
    env: [CGO_ENABLED=0]
    main: ./cmd/ravel-proxy/ravel-proxy.go
    binary: ravel-proxy
    goos:
      - linux
    goarch:
      - amd64
  - id: jailer
    env: [CGO_ENABLED=0]
    main: ./cmd/jailer/jailer.go
    binary: jailer
    goos:
      - linux
    goarch:
      - amd64
  - id: initd
    env: [CGO_ENABLED=0]
    main: ./cmd/initd/initd.go
    binary: initd
    goos:
      - linux
    goarch:
      - amd64
