[db]
path = "./tmp/corrosion.db"
[gossip]
addr = "[::]:8787"
bootstrap = []
plaintext = true

[api]
addr = "127.0.0.1:8081"
pg.addr = "127.0.0.1:5432"

[admin]
path = "/var/run/corrosion/admin.sock"

[log]
format = "json"
